### ISSUE TITLE
Error: Class 'Tco\Source\Api\Rest\V6\TcoException' not found

### ISSUE THREAD

**Issue by stefanue** [2Checkout/2checkout-php-sdk#4]
https://github.com/2Checkout/2checkout-php-sdk/blob/27e1cf8ee89b3f0670d00745b2fea0e001420cf1/src/Tco/Source/Api/Rest/V6/Order.php#L74C34-L74C3

**Comment by craigchristenson** [comment]
Thanks for reporting this issue. It has been fixed in the latest release.
